### PR TITLE
add german translation key

### PR DESCRIPTION
**Pull request by JonasunderscoreJones**
another one

### CODE REVIEW

**Review by DragonEggBedrockBreaking — APPROVED** [review]

**Comment by JonasunderscoreJones** [comment]
@DragonEggBedrockBreaking holup you got power here?

**Comment by DragonEggBedrockBreaking** [comment]
> @DragonEggBedrockBreaking holup you got power here?

No, anyone can approve a pr.

**Comment by JonasunderscoreJones** [comment]
then why can't I approve my own :sob:

**Comment by DragonEggBedrockBreaking** [comment]
> then why can't I approve my own :sob: 

Anyone except the author of a pr can approve the pr.

**Comment by ZtereoHYPE** [comment]
lgtm

**Pull request merged**
